concurrency: 
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - test
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly-2024-01-17
            target: wasm32-unknown-unknown
            override: true
      - uses: davidB/rust-cargo-make@v1

      - run: cargo install wasm-pack
      - run: cargo make build

      - if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/')
        run: |
          sed -i 's/"version": "[^"]*"/"version": "latest"/g' pkg/package.json

      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: https://npm.pkg.github.com/
          package: pkg