concurrency: 
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly-2024-01-17
            target: wasm32-unknown-unknown
            override: true
      - uses: davidB/rust-cargo-make@v1

      - run: cargo install wasm-pack
      - run: cargo make pack

      - id: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: https://npm.pkg.github.com/
          package: pkg

      - if: steps.publish.outputs.type != 'none'
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          version: "${{ steps.publish.outputs.version }}"
          git_tag_prefix: "v"
